export const sprintDashboardData = {
  projects: [
    { id: 'all', label: 'All Projects' },
    { id: 'data-analytics-engine', label: 'Data Analytics Engine' },
    { id: 'mobile-app-redesign', label: 'Mobile App Redesign' },
    { id: 'platform-api-v3', label: 'Platform API v3' },
  ],
  metrics: [
    { label: 'Total Sprints', value: '6' },
    { label: 'Completed', value: '2' },
    { label: 'Active', value: '1' },
    { label: 'Avg. Completion', value: '54%' },
  ],
  progressTrend: [
    { name: 'Sprint 11', value: 100 },
    { name: 'Sprint 7', value: 40 },
    { name: 'Sprint 5', value: 38 },
    { name: 'Sprint 12', value: 68 },
    { name: 'Sprint 8', value: 44 },
    { name: 'Sprint 13', value: 1 },
  ],
  scatterData: [
    { 
      name: 'Sprint 11 — Settings UI',
      x: 0, 
      mobileApp: [0, 100],
      dataAnalytics: null,
      platformApi: null
    },
    { 
      name: 'Sprint 7 — Schema Setup',
      x: 1, 
      mobileApp: null,
      dataAnalytics: null,
      platformApi: [1, 40]
    },
    { 
      name: 'Sprint 5 — Pipeline Setup',
      x: 2, 
      mobileApp: null,
      dataAnalytics: [2, 38],
      platformApi: null
    },
    { 
      name: 'Sprint 12 — Onboarding Flow',
      x: 3, 
      mobileApp: null,
      dataAnalytics: null,
      platformApi: [3, 68]
    },
    { 
      name: 'Sprint 8 — Auth & Endpoints',
      x: 4, 
      mobileApp: null,
      dataAnalytics: [4, 44],
      platformApi: null
    },
    { 
      name: 'Sprint 13 — Push Notifications',
      x: 5, 
      mobileApp: null,
      dataAnalytics: [5, 1],
      platformApi: null
    },
  ],
  upcomingDeadlines: [
    {
      id: 'd1',
      projectId: 'mobile-app-redesign',
      title: 'Sprint 12 — Onboarding Flow',
      subtitle: 'Mobile App Redesign',
      due: '5d',
      status: 'upcoming',
    },
    {
      id: 'd2',
      projectId: 'platform-api-v3',
      title: 'Sprint 8 — Auth & Endpoints',
      subtitle: 'Platform API v3',
      due: '6d',
      status: 'active',
    },
    {
      id: 'd3',
      projectId: 'data-analytics-engine',
      title: 'Sprint 6 — Dashboard Widgets',
      subtitle: 'Data Analytics Engine',
      due: '9d',
      status: 'active',
    },
    {
      id: 'd4',
      projectId: 'mobile-app-redesign',
      title: 'Sprint 13 — Push Notifications',
      subtitle: 'Mobile App Redesign',
      due: '19d',
      status: 'upcoming',
    },
  ],
  activity: [
    {
      id: 'a1',
      projectId: 'mobile-app-redesign',
      title: 'Sprint 13 — Push Notifications',
      subtitle: 'Mobile App Redesign',
      status: 'upcoming',
      progress: 0,
      tasks: '0/0',
    },
    {
      id: 'a2',
      projectId: 'data-analytics-engine',
      title: 'Sprint 6 — Dashboard Widgets',
      subtitle: 'Data Analytics Engine',
      status: 'active',
      progress: 27,
      tasks: '2/7',
    },
    {
      id: 'a3',
      projectId: 'mobile-app-redesign',
      title: 'Sprint 11 — Settings UI',
      subtitle: 'Mobile App Redesign',
      status: 'completed',
      progress: 100,
      tasks: '0/0',
    },
    {
      id: 'a4',
      projectId: 'platform-api-v3',
      title: 'Sprint 8 — Auth & Endpoints',
      subtitle: 'Platform API v3',
      status: 'active',
      progress: 44,
      tasks: '3/7',
    },
    {
      id: 'a6',
      projectId: 'mobile-app-redesign',
      title: 'Sprint 12 — Onboarding Flow',
      subtitle: 'Mobile App Redesign',
      status: 'active',
      progress: 67,
      tasks: '5/9',
    },
  ],
};

export const sprintProjects = [
  {
    id: 'data-analytics-engine',
    name: 'Data Analytics Engine',
    client: 'Insight Labs',
    squad: 'Dashboard Team',
    sprint: 'Sprint 6',
    startDate: '4 Apr 2026',
    endDate: '17 Apr 2026',
    health: 'Active',
    totalPoints: 45,
    donePoints: 12,
    blockers: 0,
    contributors: 6,
    releaseWindow: 'Q2 Wave 2',
    scrumMaster: 'Emma Davis',
  },
  {
    id: 'hospital-crm',
    name: 'Hospital CRM',
    client: 'HealthPlus Group',
    squad: 'Platform + Frontend',
    sprint: 'Sprint 24',
    startDate: '18 Mar 2026',
    endDate: '31 Mar 2026',
    health: 'On Track',
    totalPoints: 86,
    donePoints: 64,
    blockers: 2,
    contributors: 9,
    releaseWindow: 'Q2 Wave 1',
    scrumMaster: 'Meera Joshi',
  },
  {
    id: 'banking-portal',
    name: 'Banking Portal',
    client: 'Global Bank',
    squad: 'Core Product',
    sprint: 'Sprint 18',
    startDate: '20 Mar 2026',
    endDate: '2 Apr 2026',
    health: 'Needs Attention',
    totalPoints: 72,
    donePoints: 41,
    blockers: 4,
    contributors: 7,
    releaseWindow: 'Compliance Release',
    scrumMaster: 'Aman Khanna',
  },
  {
    id: 'travel-app',
    name: 'Travel App',
    client: 'Voyage Co.',
    squad: 'Mobile + API',
    sprint: 'Sprint 31',
    startDate: '15 Mar 2026',
    endDate: '28 Mar 2026',
    health: 'On Track',
    totalPoints: 58,
    donePoints: 49,
    blockers: 1,
    contributors: 6,
    releaseWindow: 'Summer Features',
    scrumMaster: 'Nidhi Verma',
  },
  {
    id: 'ai-chatbot',
    name: 'AI Chatbot',
    client: 'Tech Corp',
    squad: 'AI Experience',
    sprint: 'Sprint 12',
    startDate: '22 Mar 2026',
    endDate: '4 Apr 2026',
    health: 'At Risk',
    totalPoints: 68,
    donePoints: 22,
    blockers: 5,
    contributors: 8,
    releaseWindow: 'Pilot Enablement',
    scrumMaster: 'Ishaan Patel',
  },
  {
    id: 'mobile-app-redesign',
    name: 'Mobile App Redesign',
    client: 'RetailPro Group',
    squad: 'Mobile + Frontend',
    sprint: 'Sprint 11',
    startDate: '1 Apr 2026',
    endDate: '14 Apr 2026',
    health: 'Active',
    totalPoints: 52,
    donePoints: 28,
    blockers: 1,
    contributors: 5,
    releaseWindow: 'Q2 Wave 2',
    scrumMaster: 'Sarah Chen',
  },
  {
    id: 'platform-api-v3',
    name: 'Platform API v3',
    client: 'TechStack Inc.',
    squad: 'Backend + DevOps',
    sprint: 'Sprint 8',
    startDate: '5 Apr 2026',
    endDate: '18 Apr 2026',
    health: 'On Track',
    totalPoints: 68,
    donePoints: 35,
    blockers: 0,
    contributors: 7,
    releaseWindow: 'Q2 Wave 2',
    scrumMaster: 'Vikram Rao',
  },
];

export const sprintDetails = {
  'data-analytics-engine': {
    about:
      'Sprint 6 is building dashboard widgets, real-time data refresh, and analytics components for the Data Analytics Engine release.',
    kpis: [
      { title: 'Total Tasks', value: '13', detail: 'All sprint work items', tone: 'good' },
      { title: 'Completed', value: '4', detail: 'Done tasks', tone: 'good' },
      { title: 'In Progress', value: '3', detail: 'Currently active', tone: 'warning' },
      { title: 'Pending', value: '6', detail: 'Waiting in backlog', tone: 'warning' },
      { title: 'Completion Rate', value: '29%', detail: 'Progress of current sprint', tone: 'warning' },
    ],
    burndown: [
      { day: 'D1', ideal: 45, actual: 45 },
      { day: 'D2', ideal: 38, actual: 42 },
      { day: 'D3', ideal: 31, actual: 39 },
      { day: 'D4', ideal: 24, actual: 34 },
      { day: 'D5', ideal: 17, actual: 28 },
      { day: 'D6', ideal: 10, actual: 24 },
      { day: 'D7', ideal: 3, actual: 18 },
    ],
    scope: [
      { metric: 'Committed', points: 45 },
      { metric: 'Added', points: 3 },
      { metric: 'Removed', points: 0 },
      { metric: 'Completed', points: 12 },
    ],
    estimatedHours: { estimated: 160, used: 118 },
    workSplit: [
      { name: 'Done', value: 29, color: '#22c55e' },
      { name: 'In Progress', value: 29, color: '#f59e0b' },
      { name: 'To Do', value: 43, color: '#64748b' },
    ],
    board: [
      { id: 'SP-601', title: 'Export to PDF feature', owner: 'Emma', priority: 'Medium', points: 5, status: 'To Do' },
      { id: 'SP-602', title: 'Dashboard layout builder', owner: 'Emma', priority: 'Low', points: 8, status: 'To Do' },
      { id: 'SP-603', title: 'Real-time data refresh', owner: 'Carlos', priority: 'High', points: 8, status: 'To Do' },
      { id: 'SP-604', title: 'Data table with filters', owner: 'Carlos', priority: 'High', points: 8, status: 'In Progress' },
      { id: 'SP-605', title: 'KPI card component', owner: 'Emma', priority: 'Medium', points: 3, status: 'In Progress' },
      { id: 'SP-606', title: 'Line chart widget', owner: 'Emma', priority: 'High', points: 5, status: 'Done' },
      { id: 'SP-607', title: 'Bar chart widget', owner: 'Carlos', priority: 'High', points: 5, status: 'Done' },
    ],
    goals: [
      'Build core dashboard visualization widgets.',
      'Deliver filter-driven chart components for analytics views.',
      'Reduce dashboard refresh latency below 1.2s.',
    ],
    blockers: [],
    capacity: [
      { team: 'Platform', members: 4, capacity: '28 pts', utilization: '82%' },
      { team: 'Frontend', members: 3, capacity: '21 pts', utilization: '76%' },
      { team: 'QA', members: 2, capacity: '12 pts', utilization: '91%' },
    ],
    velocity: [
      { sprint: 'Sprint 5', planned: 28, completed: 11 },
      { sprint: 'Sprint 6', planned: 45, completed: 12 },
      { sprint: 'Sprint 8', planned: 32, completed: 14 },
      { sprint: 'Sprint 11', planned: 18, completed: 18 },
      { sprint: 'Sprint 12', planned: 36, completed: 24 },
    ],
    sprints: [
      { id: 'Sprint 13', title: 'Push Notifications', subtitle: 'Mobile App Redesign', status: 'upcoming', progress: 0, tasks: '0/0' },
      { id: 'Sprint 6', title: 'Dashboard Widgets', subtitle: 'Data Analytics Engine', status: 'active', progress: 27, tasks: '2/7' },
      { id: 'Sprint 11', title: 'Settings UI', subtitle: 'Mobile App Redesign', status: 'completed', progress: 100, tasks: '0/0' },
      { id: 'Sprint 8', title: 'Auth & Endpoints', subtitle: 'Platform API v3', status: 'active', progress: 44, tasks: '3/7' },
      { id: 'Sprint 12', title: 'Onboarding Flow', subtitle: 'Mobile App Redesign', status: 'active', progress: 67, tasks: '5/9' },
    ],
  },
  'hospital-crm': {
    about:
      'Hospital CRM sprint focused on role-based access, audit compliance, and billing resiliency before enterprise rollout.',
    kpis: [
      { title: 'Sprint Completion', value: '74%', detail: '64 / 86 points', tone: 'good' },
      { title: 'Defect Leakage', value: '1.9%', detail: 'Target < 2.5%', tone: 'good' },
      { title: 'Open Risks', value: '3', detail: '2 high, 1 medium', tone: 'warning' },
      { title: 'Predictability', value: '91%', detail: 'Planned vs done', tone: 'good' },
    ],
    burndown: [
      { day: 'D1', ideal: 86, actual: 86 },
      { day: 'D2', ideal: 77, actual: 80 },
      { day: 'D3', ideal: 68, actual: 73 },
      { day: 'D4', ideal: 59, actual: 67 },
      { day: 'D5', ideal: 50, actual: 58 },
      { day: 'D6', ideal: 41, actual: 49 },
      { day: 'D7', ideal: 32, actual: 38 },
      { day: 'D8', ideal: 23, actual: 30 },
      { day: 'D9', ideal: 14, actual: 22 },
      { day: 'D10', ideal: 5, actual: 14 },
    ],
    scope: [
      { metric: 'Committed', points: 86 },
      { metric: 'Added', points: 9 },
      { metric: 'Removed', points: 4 },
      { metric: 'Completed', points: 64 },
    ],
    estimatedHours: { estimated: 280, used: 212 },
    workSplit: [
      { name: 'Done', value: 46, color: '#22c55e' },
      { name: 'In Progress', value: 34, color: '#38bdf8' },
      { name: 'Review/QA', value: 12, color: '#18b7a6' },
      { name: 'Blocked', value: 8, color: '#e74c3c' },
    ],
    board: [
      {
        id: 'SP-214',
        title: 'Multi-tenant billing API hardening',
        owner: 'Priya',
        priority: 'High',
        points: 8,
        status: 'In Progress',
      },
      {
        id: 'SP-219',
        title: 'SSO onboarding flow refinement',
        owner: 'Rohan',
        priority: 'Medium',
        points: 5,
        status: 'Done',
      },
      {
        id: 'SP-221',
        title: 'Dashboard role-based permissions',
        owner: 'Anita',
        priority: 'High',
        points: 8,
        status: 'Blocked',
      },
      {
        id: 'SP-228',
        title: 'Payment retries observability',
        owner: 'Mira',
        priority: 'Medium',
        points: 5,
        status: 'Review',
      },
      {
        id: 'SP-231',
        title: 'Audit trail export improvements',
        owner: 'Dev',
        priority: 'Medium',
        points: 5,
        status: 'Done',
      },
    ],
    goals: [
      'Ship role-based access for enterprise dashboard clients.',
      'Reduce payment failure tickets by at least 30%.',
      'Close all P1 bugs before sprint review.',
      'Achieve 90% story-point predictability.',
    ],
    blockers: [
      {
        id: 'BL-11',
        title: 'Third-party billing webhook timeout spikes',
        impact: 'Payment retrials delayed for enterprise accounts',
        owner: 'Platform Team',
        eta: '26 Mar',
        severity: 'High',
      },
      {
        id: 'BL-14',
        title: 'Staging LDAP sync instability',
        impact: 'SSO QA signoff blocked for 2 stories',
        owner: 'DevOps',
        eta: '25 Mar',
        severity: 'Medium',
      },
    ],
    capacity: [
      { team: 'Platform', members: 4, capacity: '28 pts', utilization: '82%' },
      { team: 'Frontend', members: 3, capacity: '21 pts', utilization: '76%' },
      { team: 'QA', members: 2, capacity: '12 pts', utilization: '91%' },
      { team: 'DevOps', members: 2, capacity: '10 pts', utilization: '70%' },
    ],
    velocity: [
      { sprint: 'S19', planned: 36, completed: 32 },
      { sprint: 'S20', planned: 42, completed: 39 },
      { sprint: 'S21', planned: 40, completed: 34 },
      { sprint: 'S22', planned: 45, completed: 43 },
      { sprint: 'S23', planned: 44, completed: 38 },
      { sprint: 'S24', planned: 46, completed: 42 },
    ],
  },
  'banking-portal': {
    about:
      'Banking Portal sprint centered on compliance controls, audit visibility, and settlement stability ahead of regulator review.',
    kpis: [
      { title: 'Sprint Completion', value: '57%', detail: '41 / 72 points', tone: 'warning' },
      { title: 'Escaped Defects', value: '3.4%', detail: 'Target < 2.5%', tone: 'risk' },
      { title: 'Open Risks', value: '6', detail: '4 high, 2 medium', tone: 'risk' },
      { title: 'Predictability', value: '78%', detail: 'Planned vs done', tone: 'warning' },
    ],
    burndown: [
      { day: 'D1', ideal: 72, actual: 72 },
      { day: 'D2', ideal: 64, actual: 70 },
      { day: 'D3', ideal: 56, actual: 68 },
      { day: 'D4', ideal: 48, actual: 64 },
      { day: 'D5', ideal: 40, actual: 58 },
      { day: 'D6', ideal: 32, actual: 52 },
      { day: 'D7', ideal: 24, actual: 48 },
      { day: 'D8', ideal: 16, actual: 43 },
      { day: 'D9', ideal: 8, actual: 37 },
      { day: 'D10', ideal: 2, actual: 31 },
    ],
    scope: [
      { metric: 'Committed', points: 72 },
      { metric: 'Added', points: 14 },
      { metric: 'Removed', points: 2 },
      { metric: 'Completed', points: 41 },
    ],    estimatedHours: { estimated: 240, used: 186 },    workSplit: [
      { name: 'Done', value: 28, color: '#22c55e' },
      { name: 'In Progress', value: 38, color: '#38bdf8' },
      { name: 'Review/QA', value: 14, color: '#18b7a6' },
      { name: 'Blocked', value: 20, color: '#e74c3c' },
    ],
    board: [
      {
        id: 'BP-401',
        title: 'AML alerts false-positive reduction',
        owner: 'Neha',
        priority: 'High',
        points: 8,
        status: 'In Progress',
      },
      {
        id: 'BP-404',
        title: 'Maker-checker workflow refactor',
        owner: 'Arun',
        priority: 'High',
        points: 8,
        status: 'Blocked',
      },
      {
        id: 'BP-407',
        title: 'Settlement retries edge-case handling',
        owner: 'Riya',
        priority: 'Medium',
        points: 5,
        status: 'Review',
      },
      {
        id: 'BP-412',
        title: 'Compliance export audit fields',
        owner: 'Sagar',
        priority: 'Medium',
        points: 5,
        status: 'Backlog',
      },
    ],
    goals: [
      'Complete maker-checker flow hardening for all transaction types.',
      'Keep settlement retry failure under 1.5%.',
      'Clear high-severity compliance backlog before UAT.',
      'Prepare regulator-ready activity audit export.',
    ],
    blockers: [
      {
        id: 'BL-31',
        title: 'Vendor sandbox cert rotation pending',
        impact: 'Settlement simulation suite blocked',
        owner: 'Compliance IT',
        eta: '27 Mar',
        severity: 'High',
      },
      {
        id: 'BL-35',
        title: 'Legacy reconciliation service latency',
        impact: 'Daily test cycle extends by ~3 hours',
        owner: 'Core Infra',
        eta: '30 Mar',
        severity: 'High',
      },
    ],
    capacity: [
      { team: 'Core Product', members: 4, capacity: '26 pts', utilization: '88%' },
      { team: 'Compliance', members: 2, capacity: '12 pts', utilization: '94%' },
      { team: 'QA', members: 2, capacity: '11 pts', utilization: '96%' },
      { team: 'Ops', members: 1, capacity: '6 pts', utilization: '68%' },
    ],
    velocity: [
      { sprint: 'S13', planned: 34, completed: 29 },
      { sprint: 'S14', planned: 36, completed: 31 },
      { sprint: 'S15', planned: 40, completed: 35 },
      { sprint: 'S16', planned: 41, completed: 36 },
      { sprint: 'S17', planned: 44, completed: 33 },
      { sprint: 'S18', planned: 46, completed: 32 },
    ],
  },
  'travel-app': {
    about:
      'Travel App sprint focused on itinerary reliability, booking conversion, and post-booking engagement features for summer launch.',
    kpis: [
      { title: 'Sprint Completion', value: '84%', detail: '49 / 58 points', tone: 'good' },
      { title: 'Crash-Free Sessions', value: '99.1%', detail: 'Target > 99%', tone: 'good' },
      { title: 'Open Risks', value: '2', detail: '1 high, 1 medium', tone: 'warning' },
      { title: 'Predictability', value: '93%', detail: 'Planned vs done', tone: 'good' },
    ],
    burndown: [
      { day: 'D1', ideal: 58, actual: 58 },
      { day: 'D2', ideal: 52, actual: 54 },
      { day: 'D3', ideal: 46, actual: 47 },
      { day: 'D4', ideal: 40, actual: 42 },
      { day: 'D5', ideal: 34, actual: 35 },
      { day: 'D6', ideal: 28, actual: 29 },
      { day: 'D7', ideal: 22, actual: 23 },
      { day: 'D8', ideal: 16, actual: 18 },
      { day: 'D9', ideal: 10, actual: 12 },
      { day: 'D10', ideal: 4, actual: 9 },
    ],
    scope: [
      { metric: 'Committed', points: 58 },
      { metric: 'Added', points: 6 },
      { metric: 'Removed', points: 3 },
      { metric: 'Completed', points: 49 },
    ],    estimatedHours: { estimated: 200, used: 168 },    workSplit: [
      { name: 'Done', value: 52, color: '#22c55e' },
      { name: 'In Progress', value: 29, color: '#38bdf8' },
      { name: 'Review/QA', value: 11, color: '#18b7a6' },
      { name: 'Blocked', value: 8, color: '#e74c3c' },
    ],
    board: [
      {
        id: 'TA-511',
        title: 'Trip-sharing deeplink stability',
        owner: 'Mansi',
        priority: 'Medium',
        points: 5,
        status: 'Done',
      },
      {
        id: 'TA-517',
        title: 'Fare lock countdown behavior',
        owner: 'Rahul',
        priority: 'High',
        points: 8,
        status: 'In Progress',
      },
      {
        id: 'TA-521',
        title: 'Booking retry and seat map reconciliation',
        owner: 'Tanvi',
        priority: 'High',
        points: 8,
        status: 'Review',
      },
      {
        id: 'TA-526',
        title: 'Post-booking engagement notifications',
        owner: 'Imran',
        priority: 'Low',
        points: 3,
        status: 'Backlog',
      },
    ],
    goals: [
      'Maintain booking conversion improvement above 6%.',
      'Reduce itinerary change support tickets by 25%.',
      'Ship trip-sharing with deeplink reliability > 99%.',
      'Complete fare lock expiry behavior for iOS and Android.',
    ],
    blockers: [
      {
        id: 'BL-51',
        title: 'Airline seat-map service intermittent failures',
        impact: '2 stories in QA cannot complete end-to-end validation',
        owner: 'Partner Integrations',
        eta: '24 Mar',
        severity: 'Medium',
      },
    ],
    capacity: [
      { team: 'Mobile', members: 3, capacity: '20 pts', utilization: '81%' },
      { team: 'Backend', members: 2, capacity: '14 pts', utilization: '85%' },
      { team: 'QA', members: 1, capacity: '6 pts', utilization: '92%' },
    ],
    velocity: [
      { sprint: 'S26', planned: 32, completed: 30 },
      { sprint: 'S27', planned: 35, completed: 33 },
      { sprint: 'S28', planned: 37, completed: 34 },
      { sprint: 'S29', planned: 39, completed: 36 },
      { sprint: 'S30', planned: 41, completed: 39 },
      { sprint: 'S31', planned: 43, completed: 40 },
    ],
  },
  'ai-chatbot': {
    about:
      'AI Chatbot sprint is focused on reliability of retrieval pipeline, prompt safety controls, and enterprise rollout readiness.',
    kpis: [
      { title: 'Sprint Completion', value: '32%', detail: '22 / 68 points', tone: 'risk' },
      { title: 'Answer Accuracy', value: '78%', detail: 'Target > 88%', tone: 'risk' },
      { title: 'Open Risks', value: '8', detail: '5 high, 3 medium', tone: 'risk' },
      { title: 'Predictability', value: '61%', detail: 'Planned vs done', tone: 'warning' },
    ],
    burndown: [
      { day: 'D1', ideal: 68, actual: 68 },
      { day: 'D2', ideal: 60, actual: 66 },
      { day: 'D3', ideal: 52, actual: 64 },
      { day: 'D4', ideal: 44, actual: 61 },
      { day: 'D5', ideal: 36, actual: 59 },
      { day: 'D6', ideal: 28, actual: 55 },
      { day: 'D7', ideal: 20, actual: 49 },
      { day: 'D8', ideal: 12, actual: 45 },
      { day: 'D9', ideal: 6, actual: 41 },
      { day: 'D10', ideal: 2, actual: 36 },
    ],
    scope: [
      { metric: 'Committed', points: 68 },
      { metric: 'Added', points: 18 },
      { metric: 'Removed', points: 1 },
      { metric: 'Completed', points: 22 },
    ],    estimatedHours: { estimated: 220, used: 174 },    workSplit: [
      { name: 'Done', value: 19, color: '#22c55e' },
      { name: 'In Progress', value: 43, color: '#38bdf8' },
      { name: 'Review/QA', value: 11, color: '#18b7a6' },
      { name: 'Blocked', value: 27, color: '#e74c3c' },
    ],
    board: [
      {
        id: 'AI-88',
        title: 'Retriever reranking with confidence controls',
        owner: 'Sonia',
        priority: 'High',
        points: 8,
        status: 'Blocked',
      },
      {
        id: 'AI-91',
        title: 'PII redaction and prompt injection filters',
        owner: 'Nikhil',
        priority: 'High',
        points: 8,
        status: 'In Progress',
      },
      {
        id: 'AI-95',
        title: 'Hallucination feedback capture loop',
        owner: 'Ava',
        priority: 'Medium',
        points: 5,
        status: 'Review',
      },
      {
        id: 'AI-97',
        title: 'Tenant-level moderation policy controls',
        owner: 'Kabir',
        priority: 'High',
        points: 8,
        status: 'Backlog',
      },
    ],
    goals: [
      'Raise answer accuracy from 78% to at least 86%.',
      'Deploy PII-redaction for all enterprise tenants.',
      'Reduce blocked critical stories from 5 to 1.',
      'Complete rollout checklist for pilot customers.',
    ],
    blockers: [
      {
        id: 'BL-72',
        title: 'Vector DB query latency spikes under load',
        impact: 'Retriever stories fail performance acceptance criteria',
        owner: 'ML Platform',
        eta: '28 Mar',
        severity: 'High',
      },
      {
        id: 'BL-77',
        title: 'Security review pending for moderation pipeline',
        impact: 'Production rollout gated by security signoff',
        owner: 'Security Team',
        eta: '1 Apr',
        severity: 'High',
      },
    ],
    capacity: [
      { team: 'ML Platform', members: 3, capacity: '20 pts', utilization: '95%' },
      { team: 'API', members: 2, capacity: '13 pts', utilization: '89%' },
      { team: 'Web', members: 2, capacity: '12 pts', utilization: '77%' },
      { team: 'QA', members: 1, capacity: '6 pts', utilization: '92%' },
    ],
    velocity: [
      { sprint: 'S7', planned: 31, completed: 21 },
      { sprint: 'S8', planned: 33, completed: 24 },
      { sprint: 'S9', planned: 35, completed: 28 },
      { sprint: 'S10', planned: 37, completed: 26 },
      { sprint: 'S11', planned: 39, completed: 24 },
      { sprint: 'S12', planned: 42, completed: 22 },
    ],
  },
  'mobile-app-redesign': {
    about:
      'Sprint 11 focuses on mobile app UI redesign, performance optimization, and new payment flow integration.',
    kpis: [
      { title: 'Total Tasks', value: '12', detail: 'All sprint work items', tone: 'good' },
      { title: 'Completed', value: '6', detail: 'Done tasks', tone: 'good' },
      { title: 'In Progress', value: '4', detail: 'Currently active', tone: 'warning' },
      { title: 'Pending', value: '2', detail: 'Waiting in backlog', tone: 'warning' },
      { title: 'Completion Rate', value: '50%', detail: 'Progress of current sprint', tone: 'warning' },
    ],
    burndown: [
      { day: 'D1', ideal: 52, actual: 52 },
      { day: 'D2', ideal: 45, actual: 48 },
      { day: 'D3', ideal: 38, actual: 46 },
      { day: 'D4', ideal: 31, actual: 42 },
      { day: 'D5', ideal: 24, actual: 38 },
      { day: 'D6', ideal: 17, actual: 33 },
      { day: 'D7', ideal: 10, actual: 28 },
    ],
    workSplit: [
      { name: 'Done', value: 50, color: '#22c55e' },
      { name: 'In Progress', value: 33, color: '#f59e0b' },
      { name: 'To Do', value: 17, color: '#64748b' },
    ],
    board: [
      { id: 'MA-801', title: 'Mobile UI redesign mockups', owner: 'Sarah', priority: 'High', points: 8, status: 'Done' },
      { id: 'MA-802', title: 'Payment flow integration', owner: 'James', priority: 'High', points: 5, status: 'In Progress' },
      { id: 'MA-803', title: 'Performance optimization', owner: 'Sarah', priority: 'Medium', points: 5, status: 'In Progress' },
      { id: 'MA-804', title: 'Dark mode implementation', owner: 'Mike', priority: 'Low', points: 3, status: 'Done' },
      { id: 'MA-805', title: 'Testing dark mode UI', owner: 'James', priority: 'Medium', points: 3, status: 'Done' },
      { id: 'MA-806', title: 'API integration tests', owner: 'Mike', priority: 'High', points: 5, status: 'In Progress' },
      { id: 'MA-807', title: 'Push notification setup', owner: 'Sarah', priority: 'Medium', points: 3, status: 'To Do' },
      { id: 'MA-808', title: 'QA testing and bug fixes', owner: 'James', priority: 'Medium', points: 4, status: 'To Do' },
    ],
    goals: [
      'Complete mobile UI redesign with modern design patterns.',
      'Integrate new payment flow and reduce checkout failures to <2%.',
      'Achieve 60+ FPS performance on low-end devices.',
    ],
    blockers: [],
    capacity: [
      { team: 'Mobile', members: 3, capacity: '24 pts', utilization: '79%' },
      { team: 'Backend', members: 2, capacity: '14 pts', utilization: '71%' },
      { team: 'QA', members: 1, capacity: '8 pts', utilization: '75%' },
    ],
    velocity: [
      { sprint: 'Sprint 9', planned: 28, completed: 18 },
      { sprint: 'Sprint 10', planned: 32, completed: 21 },
      { sprint: 'Sprint 11', planned: 46, completed: 28 },
    ],
    sprints: [
      { id: 'Sprint 11', title: 'Settings UI', subtitle: 'Mobile App Redesign', status: 'completed', progress: 100, tasks: '0/0' },
      { id: 'Sprint 12', title: 'Onboarding Flow', subtitle: 'Mobile App Redesign', status: 'active', progress: 67, tasks: '5/9' },
      { id: 'Sprint 13', title: 'Push Notifications', subtitle: 'Mobile App Redesign', status: 'upcoming', progress: 0, tasks: '0/0' },
    ],
  },
  'platform-api-v3': {
    about:
      'Sprint 8 delivers new API endpoints, authentication hardening, rate-limiting improvements, and SDK updates.',
    kpis: [
      { title: 'Total Tasks', value: '14', detail: 'All sprint work items', tone: 'good' },
      { title: 'Completed', value: '5', detail: 'Done tasks', tone: 'good' },
      { title: 'In Progress', value: '7', detail: 'Currently active', tone: 'warning' },
      { title: 'Pending', value: '2', detail: 'Waiting in backlog', tone: 'warning' },
      { title: 'Completion Rate', value: '36%', detail: 'Progress of current sprint', tone: 'warning' },
    ],
    burndown: [
      { day: 'D1', ideal: 68, actual: 68 },
      { day: 'D2', ideal: 59, actual: 65 },
      { day: 'D3', ideal: 50, actual: 62 },
      { day: 'D4', ideal: 41, actual: 58 },
      { day: 'D5', ideal: 32, actual: 54 },
      { day: 'D6', ideal: 23, actual: 48 },
      { day: 'D7', ideal: 14, actual: 42 },
    ],
    workSplit: [
      { name: 'Done', value: 36, color: '#22c55e' },
      { name: 'In Progress', value: 50, color: '#38bdf8' },
      { name: 'To Do', value: 14, color: '#64748b' },
    ],
    board: [
      { id: 'API-601', title: 'New auth endpoints v3', owner: 'Vikram', priority: 'High', points: 8, status: 'In Progress' },
      { id: 'API-602', title: 'Rate limiting middleware', owner: 'Priya', priority: 'High', points: 5, status: 'Done' },
      { id: 'API-603', title: 'SDK updates for mobile', owner: 'Rohan', priority: 'Medium', points: 5, status: 'In Progress' },
      { id: 'API-604', title: 'API documentation update', owner: 'Vikram', priority: 'Low', points: 3, status: 'Done' },
      { id: 'API-605', title: 'Security audit for endpoints', owner: 'Priya', priority: 'High', points: 8, status: 'In Progress' },
      { id: 'API-606', title: 'Database migration scripts', owner: 'Rohan', priority: 'Medium', points: 5, status: 'In Progress' },
      { id: 'API-607', title: 'Performance load testing', owner: 'Vikram', priority: 'Medium', points: 3, status: 'To Do' },
      { id: 'API-608', title: 'Release notes prep', owner: 'Priya', priority: 'Low', points: 2, status: 'Done' },
    ],
    goals: [
      'Ship Platform API v3 with improved authentication layer.',
      'Reduce API latency by 30% through rate-limiting optimization.',
      'Achieve 99.9% uptime SLA with failover mechanisms.',
    ],
    blockers: [],
    capacity: [
      { team: 'API', members: 3, capacity: '22 pts', utilization: '82%' },
      { team: 'DevOps', members: 2, capacity: '12 pts', utilization: '75%' },
      { team: 'QA', members: 2, capacity: '11 pts', utilization: '82%' },
    ],
    velocity: [
      { sprint: 'Sprint 6', planned: 24, completed: 15 },
      { sprint: 'Sprint 7', planned: 28, completed: 18 },
      { sprint: 'Sprint 8', planned: 32, completed: 20 },
    ],
    sprints: [
      { id: 'Sprint 8', title: 'Auth & Endpoints', subtitle: 'Platform API v3', status: 'active', progress: 44, tasks: '3/7' },
    ],
  },
};
