export const sprintProjects = [
  {
    id: 'hospital-crm',
    name: 'Hospital CRM',
    client: 'HealthPlus Group',
    squad: 'Platform + Frontend',
    sprint: 'Sprint 24',
    startDate: '18 Mar 2026',
    endDate: '31 Mar 2026',
    health: 'On Track',
    totalPoints: 86,
    donePoints: 64,
    blockers: 2,
    contributors: 9,
    releaseWindow: 'Q2 Wave 1',
  },
  {
    id: 'banking-portal',
    name: 'Banking Portal',
    client: 'Global Bank',
    squad: 'Core Product',
    sprint: 'Sprint 18',
    startDate: '20 Mar 2026',
    endDate: '2 Apr 2026',
    health: 'Needs Attention',
    totalPoints: 72,
    donePoints: 41,
    blockers: 4,
    contributors: 7,
    releaseWindow: 'Compliance Release',
  },
  {
    id: 'travel-app',
    name: 'Travel App',
    client: 'Voyage Co.',
    squad: 'Mobile + API',
    sprint: 'Sprint 31',
    startDate: '15 Mar 2026',
    endDate: '28 Mar 2026',
    health: 'On Track',
    totalPoints: 58,
    donePoints: 49,
    blockers: 1,
    contributors: 6,
    releaseWindow: 'Summer Features',
  },
  {
    id: 'ai-chatbot',
    name: 'AI Chatbot',
    client: 'Tech Corp',
    squad: 'AI Experience',
    sprint: 'Sprint 12',
    startDate: '22 Mar 2026',
    endDate: '4 Apr 2026',
    health: 'At Risk',
    totalPoints: 68,
    donePoints: 22,
    blockers: 5,
    contributors: 8,
    releaseWindow: 'Pilot Enablement',
  },
];

export const sprintDetails = {
  'hospital-crm': {
    about:
      'Hospital CRM sprint focused on role-based access, audit compliance, and billing resiliency before enterprise rollout.',
    kpis: [
      { title: 'Sprint Completion', value: '74%', detail: '64 / 86 points', tone: 'good' },
      { title: 'Defect Leakage', value: '1.9%', detail: 'Target < 2.5%', tone: 'good' },
      { title: 'Open Risks', value: '3', detail: '2 high, 1 medium', tone: 'warning' },
      { title: 'Predictability', value: '91%', detail: 'Planned vs done', tone: 'good' },
    ],
    burndown: [
      { day: 'D1', ideal: 86, actual: 86 },
      { day: 'D2', ideal: 77, actual: 80 },
      { day: 'D3', ideal: 68, actual: 73 },
      { day: 'D4', ideal: 59, actual: 67 },
      { day: 'D5', ideal: 50, actual: 58 },
      { day: 'D6', ideal: 41, actual: 49 },
      { day: 'D7', ideal: 32, actual: 38 },
      { day: 'D8', ideal: 23, actual: 30 },
      { day: 'D9', ideal: 14, actual: 22 },
      { day: 'D10', ideal: 5, actual: 14 },
    ],
    scope: [
      { metric: 'Committed', points: 86 },
      { metric: 'Added', points: 9 },
      { metric: 'Removed', points: 4 },
      { metric: 'Completed', points: 64 },
    ],
    workSplit: [
      { name: 'Done', value: 46, color: '#22c55e' },
      { name: 'In Progress', value: 34, color: '#38bdf8' },
      { name: 'Review/QA', value: 12, color: '#18b7a6' },
      { name: 'Blocked', value: 8, color: '#e74c3c' },
    ],
    board: [
      {
        id: 'SP-214',
        title: 'Multi-tenant billing API hardening',
        owner: 'Priya',
        priority: 'High',
        points: 8,
        status: 'In Progress',
      },
      {
        id: 'SP-219',
        title: 'SSO onboarding flow refinement',
        owner: 'Rohan',
        priority: 'Medium',
        points: 5,
        status: 'Done',
      },
      {
        id: 'SP-221',
        title: 'Dashboard role-based permissions',
        owner: 'Anita',
        priority: 'High',
        points: 8,
        status: 'Blocked',
      },
      {
        id: 'SP-228',
        title: 'Payment retries observability',
        owner: 'Mira',
        priority: 'Medium',
        points: 5,
        status: 'Review',
      },
      {
        id: 'SP-231',
        title: 'Audit trail export improvements',
        owner: 'Dev',
        priority: 'Medium',
        points: 5,
        status: 'Done',
      },
    ],
    goals: [
      'Ship role-based access for enterprise dashboard clients.',
      'Reduce payment failure tickets by at least 30%.',
      'Close all P1 bugs before sprint review.',
      'Achieve 90% story-point predictability.',
    ],
    blockers: [
      {
        id: 'BL-11',
        title: 'Third-party billing webhook timeout spikes',
        impact: 'Payment retrials delayed for enterprise accounts',
        owner: 'Platform Team',
        eta: '26 Mar',
        severity: 'High',
      },
      {
        id: 'BL-14',
        title: 'Staging LDAP sync instability',
        impact: 'SSO QA signoff blocked for 2 stories',
        owner: 'DevOps',
        eta: '25 Mar',
        severity: 'Medium',
      },
    ],
    capacity: [
      { team: 'Platform', members: 4, capacity: '28 pts', utilization: '82%' },
      { team: 'Frontend', members: 3, capacity: '21 pts', utilization: '76%' },
      { team: 'QA', members: 2, capacity: '12 pts', utilization: '91%' },
      { team: 'DevOps', members: 2, capacity: '10 pts', utilization: '70%' },
    ],
    velocity: [
      { sprint: 'S19', planned: 36, completed: 32 },
      { sprint: 'S20', planned: 42, completed: 39 },
      { sprint: 'S21', planned: 40, completed: 34 },
      { sprint: 'S22', planned: 45, completed: 43 },
      { sprint: 'S23', planned: 44, completed: 38 },
      { sprint: 'S24', planned: 46, completed: 42 },
    ],
  },
  'banking-portal': {
    about:
      'Banking Portal sprint centered on compliance controls, audit visibility, and settlement stability ahead of regulator review.',
    kpis: [
      { title: 'Sprint Completion', value: '57%', detail: '41 / 72 points', tone: 'warning' },
      { title: 'Escaped Defects', value: '3.4%', detail: 'Target < 2.5%', tone: 'risk' },
      { title: 'Open Risks', value: '6', detail: '4 high, 2 medium', tone: 'risk' },
      { title: 'Predictability', value: '78%', detail: 'Planned vs done', tone: 'warning' },
    ],
    burndown: [
      { day: 'D1', ideal: 72, actual: 72 },
      { day: 'D2', ideal: 64, actual: 70 },
      { day: 'D3', ideal: 56, actual: 68 },
      { day: 'D4', ideal: 48, actual: 64 },
      { day: 'D5', ideal: 40, actual: 58 },
      { day: 'D6', ideal: 32, actual: 52 },
      { day: 'D7', ideal: 24, actual: 48 },
      { day: 'D8', ideal: 16, actual: 43 },
      { day: 'D9', ideal: 8, actual: 37 },
      { day: 'D10', ideal: 2, actual: 31 },
    ],
    scope: [
      { metric: 'Committed', points: 72 },
      { metric: 'Added', points: 14 },
      { metric: 'Removed', points: 2 },
      { metric: 'Completed', points: 41 },
    ],
    workSplit: [
      { name: 'Done', value: 28, color: '#22c55e' },
      { name: 'In Progress', value: 38, color: '#38bdf8' },
      { name: 'Review/QA', value: 14, color: '#18b7a6' },
      { name: 'Blocked', value: 20, color: '#e74c3c' },
    ],
    board: [
      {
        id: 'BP-401',
        title: 'AML alerts false-positive reduction',
        owner: 'Neha',
        priority: 'High',
        points: 8,
        status: 'In Progress',
      },
      {
        id: 'BP-404',
        title: 'Maker-checker workflow refactor',
        owner: 'Arun',
        priority: 'High',
        points: 8,
        status: 'Blocked',
      },
      {
        id: 'BP-407',
        title: 'Settlement retries edge-case handling',
        owner: 'Riya',
        priority: 'Medium',
        points: 5,
        status: 'Review',
      },
      {
        id: 'BP-412',
        title: 'Compliance export audit fields',
        owner: 'Sagar',
        priority: 'Medium',
        points: 5,
        status: 'Backlog',
      },
    ],
    goals: [
      'Complete maker-checker flow hardening for all transaction types.',
      'Keep settlement retry failure under 1.5%.',
      'Clear high-severity compliance backlog before UAT.',
      'Prepare regulator-ready activity audit export.',
    ],
    blockers: [
      {
        id: 'BL-31',
        title: 'Vendor sandbox cert rotation pending',
        impact: 'Settlement simulation suite blocked',
        owner: 'Compliance IT',
        eta: '27 Mar',
        severity: 'High',
      },
      {
        id: 'BL-35',
        title: 'Legacy reconciliation service latency',
        impact: 'Daily test cycle extends by ~3 hours',
        owner: 'Core Infra',
        eta: '30 Mar',
        severity: 'High',
      },
    ],
    capacity: [
      { team: 'Core Product', members: 4, capacity: '26 pts', utilization: '88%' },
      { team: 'Compliance', members: 2, capacity: '12 pts', utilization: '94%' },
      { team: 'QA', members: 2, capacity: '11 pts', utilization: '96%' },
      { team: 'Ops', members: 1, capacity: '6 pts', utilization: '68%' },
    ],
    velocity: [
      { sprint: 'S13', planned: 34, completed: 29 },
      { sprint: 'S14', planned: 36, completed: 31 },
      { sprint: 'S15', planned: 40, completed: 35 },
      { sprint: 'S16', planned: 41, completed: 36 },
      { sprint: 'S17', planned: 44, completed: 33 },
      { sprint: 'S18', planned: 46, completed: 32 },
    ],
  },
  'travel-app': {
    about:
      'Travel App sprint focused on itinerary reliability, booking conversion, and post-booking engagement features for summer launch.',
    kpis: [
      { title: 'Sprint Completion', value: '84%', detail: '49 / 58 points', tone: 'good' },
      { title: 'Crash-Free Sessions', value: '99.1%', detail: 'Target > 99%', tone: 'good' },
      { title: 'Open Risks', value: '2', detail: '1 high, 1 medium', tone: 'warning' },
      { title: 'Predictability', value: '93%', detail: 'Planned vs done', tone: 'good' },
    ],
    burndown: [
      { day: 'D1', ideal: 58, actual: 58 },
      { day: 'D2', ideal: 52, actual: 54 },
      { day: 'D3', ideal: 46, actual: 47 },
      { day: 'D4', ideal: 40, actual: 42 },
      { day: 'D5', ideal: 34, actual: 35 },
      { day: 'D6', ideal: 28, actual: 29 },
      { day: 'D7', ideal: 22, actual: 23 },
      { day: 'D8', ideal: 16, actual: 18 },
      { day: 'D9', ideal: 10, actual: 12 },
      { day: 'D10', ideal: 4, actual: 9 },
    ],
    scope: [
      { metric: 'Committed', points: 58 },
      { metric: 'Added', points: 6 },
      { metric: 'Removed', points: 3 },
      { metric: 'Completed', points: 49 },
    ],
    workSplit: [
      { name: 'Done', value: 52, color: '#22c55e' },
      { name: 'In Progress', value: 29, color: '#38bdf8' },
      { name: 'Review/QA', value: 11, color: '#18b7a6' },
      { name: 'Blocked', value: 8, color: '#e74c3c' },
    ],
    board: [
      {
        id: 'TA-511',
        title: 'Trip-sharing deeplink stability',
        owner: 'Mansi',
        priority: 'Medium',
        points: 5,
        status: 'Done',
      },
      {
        id: 'TA-517',
        title: 'Fare lock countdown behavior',
        owner: 'Rahul',
        priority: 'High',
        points: 8,
        status: 'In Progress',
      },
      {
        id: 'TA-521',
        title: 'Booking retry and seat map reconciliation',
        owner: 'Tanvi',
        priority: 'High',
        points: 8,
        status: 'Review',
      },
      {
        id: 'TA-526',
        title: 'Post-booking engagement notifications',
        owner: 'Imran',
        priority: 'Low',
        points: 3,
        status: 'Backlog',
      },
    ],
    goals: [
      'Maintain booking conversion improvement above 6%.',
      'Reduce itinerary change support tickets by 25%.',
      'Ship trip-sharing with deeplink reliability > 99%.',
      'Complete fare lock expiry behavior for iOS and Android.',
    ],
    blockers: [
      {
        id: 'BL-51',
        title: 'Airline seat-map service intermittent failures',
        impact: '2 stories in QA cannot complete end-to-end validation',
        owner: 'Partner Integrations',
        eta: '24 Mar',
        severity: 'Medium',
      },
    ],
    capacity: [
      { team: 'Mobile', members: 3, capacity: '20 pts', utilization: '81%' },
      { team: 'Backend', members: 2, capacity: '14 pts', utilization: '85%' },
      { team: 'QA', members: 1, capacity: '6 pts', utilization: '92%' },
    ],
    velocity: [
      { sprint: 'S26', planned: 32, completed: 30 },
      { sprint: 'S27', planned: 35, completed: 33 },
      { sprint: 'S28', planned: 37, completed: 34 },
      { sprint: 'S29', planned: 39, completed: 36 },
      { sprint: 'S30', planned: 41, completed: 39 },
      { sprint: 'S31', planned: 43, completed: 40 },
    ],
  },
  'ai-chatbot': {
    about:
      'AI Chatbot sprint is focused on reliability of retrieval pipeline, prompt safety controls, and enterprise rollout readiness.',
    kpis: [
      { title: 'Sprint Completion', value: '32%', detail: '22 / 68 points', tone: 'risk' },
      { title: 'Answer Accuracy', value: '78%', detail: 'Target > 88%', tone: 'risk' },
      { title: 'Open Risks', value: '8', detail: '5 high, 3 medium', tone: 'risk' },
      { title: 'Predictability', value: '61%', detail: 'Planned vs done', tone: 'warning' },
    ],
    burndown: [
      { day: 'D1', ideal: 68, actual: 68 },
      { day: 'D2', ideal: 60, actual: 66 },
      { day: 'D3', ideal: 52, actual: 64 },
      { day: 'D4', ideal: 44, actual: 61 },
      { day: 'D5', ideal: 36, actual: 59 },
      { day: 'D6', ideal: 28, actual: 55 },
      { day: 'D7', ideal: 20, actual: 49 },
      { day: 'D8', ideal: 12, actual: 45 },
      { day: 'D9', ideal: 6, actual: 41 },
      { day: 'D10', ideal: 2, actual: 36 },
    ],
    scope: [
      { metric: 'Committed', points: 68 },
      { metric: 'Added', points: 18 },
      { metric: 'Removed', points: 1 },
      { metric: 'Completed', points: 22 },
    ],
    workSplit: [
      { name: 'Done', value: 19, color: '#22c55e' },
      { name: 'In Progress', value: 43, color: '#38bdf8' },
      { name: 'Review/QA', value: 11, color: '#18b7a6' },
      { name: 'Blocked', value: 27, color: '#e74c3c' },
    ],
    board: [
      {
        id: 'AI-88',
        title: 'Retriever reranking with confidence controls',
        owner: 'Sonia',
        priority: 'High',
        points: 8,
        status: 'Blocked',
      },
      {
        id: 'AI-91',
        title: 'PII redaction and prompt injection filters',
        owner: 'Nikhil',
        priority: 'High',
        points: 8,
        status: 'In Progress',
      },
      {
        id: 'AI-95',
        title: 'Hallucination feedback capture loop',
        owner: 'Ava',
        priority: 'Medium',
        points: 5,
        status: 'Review',
      },
      {
        id: 'AI-97',
        title: 'Tenant-level moderation policy controls',
        owner: 'Kabir',
        priority: 'High',
        points: 8,
        status: 'Backlog',
      },
    ],
    goals: [
      'Raise answer accuracy from 78% to at least 86%.',
      'Deploy PII-redaction for all enterprise tenants.',
      'Reduce blocked critical stories from 5 to 1.',
      'Complete rollout checklist for pilot customers.',
    ],
    blockers: [
      {
        id: 'BL-72',
        title: 'Vector DB query latency spikes under load',
        impact: 'Retriever stories fail performance acceptance criteria',
        owner: 'ML Platform',
        eta: '28 Mar',
        severity: 'High',
      },
      {
        id: 'BL-77',
        title: 'Security review pending for moderation pipeline',
        impact: 'Production rollout gated by security signoff',
        owner: 'Security Team',
        eta: '1 Apr',
        severity: 'High',
      },
    ],
    capacity: [
      { team: 'ML Platform', members: 3, capacity: '20 pts', utilization: '95%' },
      { team: 'API', members: 2, capacity: '13 pts', utilization: '89%' },
      { team: 'Web', members: 2, capacity: '12 pts', utilization: '77%' },
      { team: 'QA', members: 1, capacity: '6 pts', utilization: '92%' },
    ],
    velocity: [
      { sprint: 'S7', planned: 31, completed: 21 },
      { sprint: 'S8', planned: 33, completed: 24 },
      { sprint: 'S9', planned: 35, completed: 28 },
      { sprint: 'S10', planned: 37, completed: 26 },
      { sprint: 'S11', planned: 39, completed: 24 },
      { sprint: 'S12', planned: 42, completed: 22 },
    ],
  },
};
