export const kpiCards = [
  { title: 'Total Headcount', value: '247', delta: '+12.3% vs last quarter', tone: 'mint' },
  { title: 'New Hires Q1', value: '34', delta: '+8.2% YoY growth', tone: 'blue' },
  { title: 'Attrition Rate', value: '4.2%', delta: '-1.1% vs 5.3% last year', tone: 'lavender' },
  { title: 'Avg Performance', value: '4.65', delta: '+0.3 out of 5.0', tone: 'amber' },
  { title: 'Present Today', value: '231', delta: '93.5% biometric verified', tone: 'cyan' },
  { title: 'Active Projects', value: '18', delta: '+4 across all teams', tone: 'pink' },
];

export const trendValues = [216, 224, 228, 234, 241, 247];
export const trendLabels = ['Oct', 'Nov', 'Dec', 'Jan', 'Feb', 'Mar'];

export const departmentDistribution = [
  { name: 'Eng', count: 82, color: '#2f71c7' },
  { name: 'Sales', count: 42, color: '#18b7a6' },
  { name: 'Mktg', count: 35, color: '#f0a84b' },
  { name: 'Product', count: 28, color: '#38bdf8' },
  { name: 'Ops', count: 24, color: '#22c55e' },
  { name: 'Finance', count: 16, color: '#0ca8c7' },
  { name: 'Design', count: 10, color: '#66a3ff' },
  { name: 'HR', count: 10, color: '#667085' },
];

export const alerts = [
  { text: '2 senior engineers submitted resignation', tag: 'Retention Risk', color: 'danger' },
  { text: 'Sales team exceeded Q1 target by 22%', tag: 'Win', color: 'success' },
  { text: '3 key roles unfilled 60+ days', tag: 'Hiring Gap', color: 'danger' },
  { text: 'Engineering velocity up 18% this sprint', tag: 'Productivity', color: 'success' },
  { text: 'Employee satisfaction dropped to 7.2/10', tag: 'Morale', color: 'warning' },
  { text: 'DEI hiring goals on track at 48%', tag: 'DEI', color: 'success' },
];

export const activeProjects = [
  { name: 'Platform v3.0 Rebuild', team: 'Engineering', members: 18, due: 'Apr 15', progress: 72, status: 'On Track', color: '#18b7a6' },
  { name: 'Q1 Enterprise Sales Drive', team: 'Sales', members: 8, due: 'Mar 31', progress: 88, status: 'Ahead', color: '#2f71c7' },
  { name: 'Spring Marketing Campaign', team: 'Marketing', members: 6, due: 'Apr 1', progress: 55, status: 'At Risk', color: '#f0a84b' },
  { name: '2026 Product Roadmap', team: 'Product', members: 5, due: 'Mar 20', progress: 95, status: 'Ahead', color: '#38bdf8' },
  { name: 'Brand Identity Refresh', team: 'Design', members: 4, due: 'Apr 30', progress: 40, status: 'On Track', color: '#22c55e' },
];

export const topPerformers = [
  { name: 'Sarah Chen', project: 'Platform v3.0', rating: 4.9, initials: 'SC', tone: 'violet' },
  { name: 'James Wilson', project: 'Q1 Enterprise Drive', rating: 4.8, initials: 'JW', tone: 'indigo' },
  { name: 'Priya Patel', project: 'Roadmap 2026', rating: 4.8, initials: 'PP', tone: 'emerald' },
  { name: 'Marcus Lee', project: 'Spring Campaign', rating: 4.7, initials: 'ML', tone: 'amber' },
  { name: 'Elena Torres', project: 'Brand Refresh', rating: 4.7, initials: 'ET', tone: 'pink' },
];

export const members = [
  {
    id: 1,
    name: 'Sarah Chen',
    role: 'VP of Engineering',
    initials: 'SC',
    status: 'Active',
    attendanceStatus: 'Present',
    checkIn: '08:52',
    project: 'Platform v3.0 Rebuild',
    done: 21,
    open: 4,
    rating: 4.9,
    location: 'San Francisco',
    biometric: ['Face', 'Fingerprint'],
    badgeTone: 'violet',
    salary: '$195K',
    employeeCode: 'EMP001',
    email: 'sarah.chen@northstar.com',
    phone: '+1 415 555 0101',
    department: 'Engineering',
    performance: '4.9/5',
    since: 'Mar 2022',
    workStatus: 'Active',
    skills: ['React', 'Node.js', 'System Design'],
  },
  {
    id: 2,
    name: 'James Wilson',
    role: 'Sales Director',
    initials: 'JW',
    status: 'Active',
    attendanceStatus: 'Late',
    checkIn: '09:41',
    project: 'Q1 Enterprise Sales Drive',
    done: 40,
    open: 2,
    rating: 4.8,
    location: 'New York',
    biometric: ['Fingerprint'],
    badgeTone: 'indigo',
    salary: '$176K',
    employeeCode: 'EMP002',
    email: 'james.wilson@northstar.com',
    phone: '+1 917 555 0142',
    department: 'Sales',
    performance: '4.8/5',
    since: 'Jan 2021',
    workStatus: 'Active',
    skills: ['Negotiation', 'Forecasting', 'CRM'],
  },
  {
    id: 3,
    name: 'Priya Patel',
    role: 'Head of Product',
    initials: 'PP',
    status: 'Active',
    attendanceStatus: 'Present',
    checkIn: '08:30',
    project: '2026 Product Roadmap',
    done: 21,
    open: 1,
    rating: 4.8,
    location: 'San Francisco',
    biometric: ['Face', 'Print'],
    badgeTone: 'emerald',
    salary: '$182K',
    employeeCode: 'EMP003',
    email: 'priya.patel@northstar.com',
    phone: '+1 628 555 0108',
    department: 'Product',
    performance: '4.8/5',
    since: 'Jul 2022',
    workStatus: 'Active',
    skills: ['Roadmapping', 'Strategy', 'Research'],
  },
  {
    id: 4,
    name: 'Marcus Lee',
    role: 'Marketing Manager',
    initials: 'ML',
    status: 'Active',
    attendanceStatus: 'Present',
    checkIn: '09:00',
    project: 'Spring Marketing Campaign',
    done: 13,
    open: 8,
    rating: 4.7,
    location: 'Austin',
    biometric: ['Facial'],
    badgeTone: 'amber',
    salary: '$148K',
    employeeCode: 'EMP004',
    email: 'marcus.lee@northstar.com',
    phone: '+1 512 555 0197',
    department: 'Marketing',
    performance: '4.7/5',
    since: 'May 2023',
    workStatus: 'Active',
    skills: ['Brand', 'Campaigns', 'Content'],
  },
  {
    id: 5,
    name: 'Elena Torres',
    role: 'Lead Designer',
    initials: 'ET',
    status: 'Remote',
    attendanceStatus: 'Present',
    checkIn: '10:05',
    project: 'Brand Identity Refresh',
    done: 9,
    open: 5,
    rating: 4.7,
    location: 'Remote',
    biometric: ['Facial'],
    badgeTone: 'pink',
    salary: '$142K',
    employeeCode: 'EMP005',
    email: 'elena.torres@northstar.com',
    phone: '+1 305 555 0184',
    department: 'Design',
    performance: '4.7/5',
    since: 'Sep 2023',
    workStatus: 'Remote',
    skills: ['Figma', 'UX', 'Design Systems'],
  },
  {
    id: 6,
    name: 'Alex Kim',
    role: 'Sr. Frontend Engineer',
    initials: 'AK',
    status: 'Active',
    attendanceStatus: 'Present',
    checkIn: '08:45',
    project: 'Platform v3.0 Rebuild',
    done: 18,
    open: 6,
    rating: 4.5,
    location: 'San Francisco',
    biometric: ['Face', 'Print'],
    badgeTone: 'blue',
    salary: '$151K',
    employeeCode: 'EMP006',
    email: 'alex.kim@northstar.com',
    phone: '+1 415 555 0162',
    department: 'Engineering',
    performance: '4.5/5',
    since: 'Apr 2024',
    workStatus: 'Active',
    skills: ['React', 'Vite', 'Accessibility'],
  },
  {
    id: 7,
    name: 'Anna Kowalski',
    role: 'HR Director',
    initials: 'AK',
    status: 'Active',
    attendanceStatus: 'Present',
    checkIn: '09:00',
    project: 'Q1 Hiring Drive',
    done: 22,
    open: 7,
    rating: 4.4,
    location: 'San Francisco',
    biometric: ['Fingerprint'],
    badgeTone: 'teal',
    salary: '$139K',
    employeeCode: 'EMP007',
    email: 'anna.kowalski@northstar.com',
    phone: '+1 415 555 0127',
    department: 'HR',
    performance: '4.4/5',
    since: 'Jan 2020',
    workStatus: 'Active',
    skills: ['Talent', 'People Ops', 'Compliance'],
  },
  {
    id: 8,
    name: 'Li Wei',
    role: 'Data Scientist',
    initials: 'LW',
    status: 'Active',
    attendanceStatus: 'Present',
    checkIn: '08:30',
    project: 'ML Recommendation Engine',
    done: 8,
    open: 9,
    rating: 4.6,
    location: 'San Francisco',
    biometric: ['Face', 'Print'],
    badgeTone: 'purple',
    salary: '$159K',
    employeeCode: 'EMP008',
    email: 'li.wei@northstar.com',
    phone: '+1 650 555 0188',
    department: 'Engineering',
    performance: '4.6/5',
    since: 'Feb 2024',
    workStatus: 'Active',
    skills: ['Python', 'ML Ops', 'Statistics'],
  },
  {
    id: 9,
    name: "Ryan O'Brien",
    role: 'Sales Manager',
    initials: 'RO',
    status: 'Active',
    attendanceStatus: 'Late',
    checkIn: '10:15',
    project: 'Q1 Enterprise Sales Drive',
    done: 37,
    open: 3,
    rating: 4.4,
    location: 'New York',
    biometric: ['Fingerprint'],
    badgeTone: 'green',
    salary: '$141K',
    employeeCode: 'EMP009',
    email: 'ryan.obrien@northstar.com',
    phone: '+1 917 555 0131',
    department: 'Sales',
    performance: '4.4/5',
    since: 'Nov 2021',
    workStatus: 'Active',
    skills: ['Enterprise', 'Pipeline', 'B2B Sales'],
  },
  {
    id: 10,
    name: 'Sofia Garcia',
    role: 'Marketing Lead',
    initials: 'SG',
    status: 'On Leave',
    attendanceStatus: 'On Leave',
    checkIn: '--:--',
    project: 'Spring Marketing Campaign',
    done: 8,
    open: 0,
    rating: 4.2,
    location: 'Austin',
    biometric: ['Facial'],
    badgeTone: 'orange',
    salary: '$134K',
    employeeCode: 'EMP010',
    email: 'sofia.garcia@northstar.com',
    phone: '+1 512 555 0149',
    department: 'Marketing',
    performance: '4.2/5',
    since: 'Mar 2024',
    workStatus: 'On Leave',
    skills: ['Campaign Ops', 'Social', 'Analytics'],
  },
  {
    id: 11,
    name: 'Maya Singh',
    role: 'Product Designer',
    initials: 'MS',
    status: 'Active',
    attendanceStatus: 'Absent',
    checkIn: '--:--',
    project: 'Brand Identity Refresh',
    done: 10,
    open: 4,
    rating: 4.3,
    location: 'Remote',
    biometric: ['Not enrolled'],
    badgeTone: 'magenta',
    salary: '$128K',
    employeeCode: 'EMP011',
    email: 'maya.singh@northstar.com',
    phone: '+1 408 555 0158',
    department: 'Design',
    performance: '4.3/5',
    since: 'Dec 2024',
    workStatus: 'Active',
    skills: ['UI Design', 'Prototyping', 'Typography'],
  },
  {
    id: 12,
    name: 'David Brown',
    role: 'CFO',
    initials: 'DB',
    status: 'Active',
    attendanceStatus: 'Present',
    checkIn: '07:55',
    project: 'Budget Forecast 2026',
    done: 12,
    open: 2,
    rating: 4.6,
    location: 'New York',
    biometric: ['Fingerprint'],
    badgeTone: 'slate',
    salary: '$210K',
    employeeCode: 'EMP012',
    email: 'david.brown@northstar.com',
    phone: '+1 212 555 0161',
    department: 'Finance',
    performance: '4.6/5',
    since: 'Oct 2019',
    workStatus: 'Active',
    skills: ['Finance', 'Modeling', 'Operations'],
  },
];

export const attendanceSummaryCards = [
  { title: 'Present Today', value: 10, percent: '83%', tone: 'present', percentTone: 'present' },
  { title: 'Absent', value: 1, percent: '8%', tone: 'absent', percentTone: 'absent' },
  { title: 'Late Arrivals', value: 2, percent: '17%', tone: 'late', percentTone: 'late' },
  { title: 'On Leave', value: 1, percent: '8%', tone: 'leave', percentTone: 'leave' },
];

export const biometricCards = [
  {
    key: 'facial',
    title: 'Facial Recognition',
    subtitle: 'AI-powered biometric',
    enrolled: 7,
    scannedToday: 6,
    accuracy: '99.2%',
    scannedPercent: 86,
    devices: 'Devices: CAM-SF-01, CAM-REMOTE-03, CAM-NY-01',
    tone: 'face',
  },
  {
    key: 'fingerprint',
    title: 'Fingerprint Scanner',
    subtitle: 'Capacitive sensor tech',
    enrolled: 5,
    scannedToday: 5,
    accuracy: '99.8%',
    scannedPercent: 100,
    devices: 'Devices: FP-SF-03, FP-NY-02, FP-AU-01',
    tone: 'print',
  },
];

export const attendanceDays = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Today'];

export const attendanceSeries = {
  present: [10, 11, 9, 10, 8, 3, 9],
  late: [1, 0, 2, 1, 3, 0, 2],
  absent: [1, 1, 1, 1, 1, 9, 1],
};

export const attendanceLog = [
  { name: 'Sarah Chen', code: 'EMP001', department: 'Engineering', checkIn: '08:52', checkOut: '18:10', hours: '9.3h', method: 'Facial', device: 'CAM-SF-01', status: 'Present', initials: 'SC' },
  { name: 'James Wilson', code: 'EMP002', department: 'Sales', checkIn: '09:41', checkOut: '19:05', hours: '9.4h', method: 'Fingerprint', device: 'FP-NY-02', status: 'Late', initials: 'JW' },
  { name: 'Priya Patel', code: 'EMP003', department: 'Product', checkIn: '08:30', checkOut: '17:45', hours: '9.25h', method: 'Facial', device: 'CAM-SF-01', status: 'Present', initials: 'PP' },
  { name: 'Marcus Lee', code: 'EMP004', department: 'Marketing', checkIn: '09:00', checkOut: '18:30', hours: '9.5h', method: 'Fingerprint', device: 'FP-AU-01', status: 'Present', initials: 'ML' },
  { name: 'Elena Torres', code: 'EMP005', department: 'Design', checkIn: '10:05', checkOut: '18:45', hours: '8.67h', method: 'Facial', device: 'CAM-REMOTE-03', status: 'Present', initials: 'ET' },
];

export const statusTone = {
  Present: 'present',
  Late: 'late',
  Absent: 'absent',
  'On Leave': 'on-leave',
};

export const statusChipTone = {
  Active: 'active',
  Remote: 'remote',
  'On Leave': 'leave',
};

export const projectStatusTone = {
  'On Track': 'on-track',
  Ahead: 'ahead',
  'At Risk': 'risk',
};

export const formatPercent = (value) => `${value}%`;
